//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiLogs
    {
        public int LogID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Endpoint { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public string Response { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
